#!/bin/bash
# Job name:
#SBATCH --job-name=misalignment_myers_data
#
# Partition
#SBATCH --partition=henyey
#
# QoS:
#SBATCH --qos=small
#
# Processors:
#SBATCH --nodes=3
#SBATCH --ntasks-per-node=4
#
# Wall Clock Time:
#SBATCH --time=24:00:00
#

## Run Command
mv /clusterfs/henyey/dfielding/charles/charles/wind/inputs_m /clusterfs/henyey/dfielding/charles/charles/wind/inputs

mpirun -np 12 python analyzer_charles_wind.py --parallel

mv /clusterfs/henyey/dfielding/charles/charles/wind/inputs /clusterfs/henyey/dfielding/charles/charles/wind/inputs_m
