#!/bin/bash
# Job name:
#SBATCH --job-name=cnw_shell
#
# Partition
#SBATCH --partition=henyey
#
# QoS:
#SBATCH --qos=small
#
# Processors:
#SBATCH --nodes=3
#SBATCH --ntasks-per-node=4
#
# Wall Clock Time:
#SBATCH --time=12:00:00
#
# Mail type:
#SBATCH --mail-type=all
#
# Mail user:
#SBATCH --mail-user=dfielding@berkeley.edu

## Run Command
mpirun -np 12 python shell_analyzer_cnw.py --parallel

